/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jekton_passkeeper_password_CipherParamsKeeper */

#ifndef _Included_com_jekton_passkeeper_password_CipherParamsKeeper
#define _Included_com_jekton_passkeeper_password_CipherParamsKeeper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jekton_passkeeper_password_CipherParamsKeeper
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jekton_passkeeper_password_CipherParamsKeeper_getIv
  (JNIEnv *, jclass);

/*
 * Class:     com_jekton_passkeeper_password_CipherParamsKeeper
 * Method:    getSalt
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jekton_passkeeper_password_CipherParamsKeeper_getSalt
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
