/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jekton_passkeeper_password_params_InternalParamsProvider */

#ifndef _Included_com_jekton_passkeeper_password_params_InternalParamsProvider
#define _Included_com_jekton_passkeeper_password_params_InternalParamsProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jekton_passkeeper_password_params_InternalParamsProvider
 * Method:    doGetIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jekton_passkeeper_password_params_InternalParamsProvider_doGetIv
  (JNIEnv *, jobject);

/*
 * Class:     com_jekton_passkeeper_password_params_InternalParamsProvider
 * Method:    getSalt
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_jekton_passkeeper_password_params_InternalParamsProvider_getSalt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
